### ISSUE TITLE
Add android manifest in signupsignin

### ISSUE THREAD

**Issue by MckinellGreen7** [Sat-Star/MAD_Lab#1]

**Comment by MckinellGreen7** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.SignInSignUp"
        tools:targetApi="31">
        <activity
            android:name=".MainActivity"
            android:exported="true">
        </activity>
        <activity android:name=".SignIn" />
        <activity android:name=".SignUp"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>`

**Comment by Sat-Star** [comment]
Fixed

**Comment by Sat-Star** [comment]
Done
